### ISSUE TITLE
Can't exclude images attached to a specific custom post type

### ISSUE THREAD

**Issue by al1138** [GoogleChromeLabs/wp-sitemaps#231] opened 2020-09-08 08:36 UTC
**Describe the bug**
I removed a custom post type using the "wp_sitemaps_post_types" filter but images attached to those CPT are still listed in the sitemap.

**Expected behavior**
I expect to remove all related content from a custom post type if I filter this CPT

**Comment by swissspidy** [comment] 2020-09-08 08:51
@al1138 Since this feature has been merged into WordPress core, please report this at http://core.trac.wordpress.org/

Note that this is working as designed though. The `wp_sitemaps_post_types` filter is for disabling sitemaps for a certain post type. It does not handle side effects like dealing with other content attached to that post type.

To omit certain attachments, use the `wp_sitemaps_posts_query_args` filter.

**Closed as completed by swissspidy** 2020-09-08 08:51 UTC
Labels: Type: Bug
