### ISSUE TITLE
Remove trailing slash

### ISSUE THREAD

**Issue by superpoincare** [GoogleChromeLabs/wp-sitemaps#134] opened 2020-02-25 16:46 UTC
### Description

**Is your feature request related to a problem? Please describe.**
https://www.example.com/sitemap.xml and https://www.example.com/sitemap.xml/ are different pages

**Describe the solution you'd like**
https://www.example.com/sitemap.xml/ should redirect to https://www.example.com/sitemap.xml

**Comment by swissspidy** [comment] 2020-03-03 14:20
Hmm WordPress doesn't remove trailing slash for `/robots.txt` either.

**Comment by swissspidy** [comment] 2020-03-04 11:28
Although there is `\Core_Sitemaps_Index::redirect_canonical`...

**Comment by adamsilverstein** [comment] 2020-05-01 22:04
@vijayaraghavanramanan do you have any more details about the reasoning for this change? Is this required/expected behavior?

I do see that core's `robots.txt` does also work with a trailing slash (`/robots.txt/`).

**Comment by felixarntz** [comment] 2020-05-01 23:19
I tend to agree with @vijayaraghavanramanan that the sitemap URLs shouldn't support trailing slashes, as they're not directories. It's interesting that WordPress's `robots.txt` version also works with trailing slashes, my first hunch would be that that was simply an oversight - no reason for us to not handle it better here. :)

**Comment by swissspidy** [comment] 2020-05-05 14:48
This is how Meta just solved this on their end:

https://meta.trac.wordpress.org/changeset/9818/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-themes/functions.php

**Comment by swissspidy** [comment] 2020-05-05 14:55
Oh, here's the core ticket for `robots.txt`, including a patch & tests: https://core.trac.wordpress.org/ticket/48025

I guess in core we could solve this the same for sitemaps, adding methods like `is_sitemap` and such.

**Comment by jdevalk** [comment] 2020-05-12 15:10
I've just asked @sergeybiryukov to get that patch in for `robots.txt`.

**Comment by Rajesh-Techblissonline** [comment] 2020-05-27 07:58
> Oh, here's the core ticket for `robots.txt`, including a patch & tests: https://core.trac.wordpress.org/ticket/48025
> 
> I guess in core we could solve this the same for sitemaps, adding methods like `is_sitemap` and such.

What is causing this? I don't experience this on my sites! Both robots.txt and sitemap.xml works as expected! Strange!

**Comment by swissspidy** [comment] 2020-06-03 15:38
Closing as this will be handled in https://github.com/WordPress/wordpress-develop/pull/310

**Closed as completed by swissspidy** 2020-06-03 15:38 UTC
Labels: Type: Bug, needs-input, good first issue
